# action to dec
dataset: GTA
model_name: GRU_POSE
model_specs:
  input_dim: 63
  dct_n: 60
  aux_dim: 0 # auxilliary data 10 beta + 1 gender
  point_extra_feat: 0
  point_feat: 2048
  nh_rnn: 128
  nz: 128
  nk: 1
  rnn_type: gru
  x_birnn: false
  root_net_is_bn: true
  wscene: false
  wcont: true
  lambdas: [ 1.0,    0.1,    0.1]

dataset_specs:
  t_his: 30
  t_pred: 60
  data_file: ./data/data_v2_downsample0.02/
#  data_file: /home/wei/Documents/1T/GTA-IM-Dataset/data_v2_downsample0.02/
  random_rot: true
  num_scene_points: 20000
  num_cont_points: 1000
  step: 5
  sigma: 0.2

lr: 5.e-4
batch_size: 32
num_epoch: 1
num_epoch_fix: 1
save_model_interval: 1
